openapi: 3.0.1
info:
  title: Wallet Test Client API
  description: No description available
  version: v1
servers:
- url: /serviceName/client-api/v1
  description: The server
tags:
- name: wallet test client api
paths:
  /wallet/paymentcards:
    summary: Payment Cards
    description: No description available
    get:
      tags:
      - wallet
      summary: Returns available payment card details for user, optionally filtered
        by nameOnCard.
      description: Returns available payment card details for user, optionally filtered
        by nameOnCard
      operationId: getPaymentcards
      parameters:
      - name: nameOnCard
        in: query
        description: Filter by the cardholder's name (case-insensitive), can be the
          first one or more characters of one of the words/names
        required: false
        schema:
          type: string
        examples:
          example:
            summary: example
            value: Smi
      - name: dateTimeOnly
        in: query
        description: Creation date in datetime-only format
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: 2017-10-04T14:54:36
      - name: dateTime
        in: query
        description: Creation date in Zoned RFC3339 Date-time format
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: 2017-10-04T14:54:36Z
      - name: dateTime2616
        in: query
        description: Zoned RFC2616 Date-time param example
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: Wed, 4 Jul 2001 12:08:56 PDT
      - name: date
        in: query
        description: Date-only param example
        required: false
        schema:
          type: string
          format: date
        examples:
          example:
            summary: example
            value: 2017-10-04
      - name: time
        in: query
        description: time-only param example
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: 14:54:36
      - name: orderBy
        in: query
        description: |
          Order by field: nameOnCard
        required: false
        schema:
          type: string
        examples:
          example:
            summary: example
      - name: direction
        in: query
        description: Direction
        required: false
        schema:
          type: string
          enum:
          - ASC
          - DESC
          default: DESC
        examples:
          example:
            summary: example
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentCards'
              examples:
                example:
                  value: |-
                    [ {
                      "id" : "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1",
                      "pan" : "5434111122223333",
                      "cvc" : "123",
                      "startDate" : "0116",
                      "expiryDate" : "1219",
                      "nameOnCard" : "Mr Timmy Tester",
                      "creationDate" : "2011-05-30T12:13:14+03:00",
                      "balance" : {
                        "amount" : "2001",
                        "currencyCode" : "EUR"
                      },
                      "apr" : 12.75
                    }, {
                      "id" : "d593c212-70ad-41a6-a547-d5d9232414cb",
                      "pan" : "5434111122224444",
                      "cvc" : "101",
                      "startDate" : "0216",
                      "expiryDate" : "0120",
                      "nameOnCard" : "Mr Timmothy Tester",
                      "creationDate" : "2011-05-30T12:13:14+03:00",
                      "balance" : {
                        "amount" : "4.4399999999999995",
                        "currencyCode" : "GBP"
                      },
                      "apr" : 12.75
                    }, {
                      "id" : "9635966b-28e9-4479-8121-bb7bc9beeb62",
                      "pan" : "5434121212121212",
                      "cvc" : "121",
                      "startDate" : "0115",
                      "expiryDate" : "1218",
                      "nameOnCard" : "Mr Timmy Tester",
                      "creationDate" : "2011-05-30T12:13:14+03:00",
                      "balance" : {
                        "amount" : "1981",
                        "currencyCode" : "EUR"
                      },
                      "apr" : 12.75
                    } ]
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Bad Request",
                      "errors" : [ {
                        "message" : "Value Exceeded. Must be between {min} and {max}.",
                        "key" : "common.api.shoesize",
                        "context" : {
                          "max" : "50",
                          "min" : "1"
                        }
                      } ]
                    }
        "406":
          description: NotAcceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotAcceptableError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Could not find acceptable representation",
                      "supportedMediaTypes" : [ "application/json" ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to an insufficient user quota of {quota}.",
                        "key" : "common.api.quota",
                        "context" : {
                          "quota" : "someQuota"
                        }
                      } ]
                    }
        "415":
          description: UnsupportedMediaType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Unsupported media type.",
                      "errors" : [ {
                        "message" : "The request entity has a media type {mediaType} which the resource does not support.",
                        "key" : "common.api.mediaType",
                        "context" : {
                          "mediaType" : "application/javascript"
                        }
                      } ]
                    }
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Resource not found.",
                      "errors" : [ {
                        "message" : "Unable to find the resource requested resource: {resource}.",
                        "key" : "common.api.resource",
                        "context" : {
                          "resource" : "aResource"
                        }
                      } ]
                    }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedAltError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to invalid credentials.",
                        "key" : "common.api.token",
                        "context" : {
                          "accessToken" : "expired"
                        }
                      } ]
                    }
      x-BbAccessControl-resource: WALLET
      x-BbAccessControl-function: MANAGE_PAYMENT_CARDS
      x-BbAccessControl-privilege: READ_PAYMENT_CARD
    post:
      tags:
      - wallet
      summary: Adds a payment card to the user's wallet.
      description: Adds a payment card to the user's wallet
      operationId: postPaymentcards
      parameters:
      - name: X-Request-Id
        in: header
        description: Correlates HTTP requests between a client and server.
        required: false
        schema:
          type: string
        examples:
          example:
            summary: example
            value: f058ebd6-02f7-4d3f-942e-904344e8cde5
      requestBody:
        description: Adds a payment card to the user's wallet
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCard'
            examples:
              example:
                value: |-
                  {
                    "id" : "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1",
                    "pan" : "5434111122223333",
                    "cvc" : "123",
                    "startDate" : "0116",
                    "expiryDate" : "1219",
                    "nameOnCard" : "Mr Timmy Tester",
                    "creationDate" : "2011-05-30T12:13:14+03:00",
                    "balance" : {
                      "amount" : "1000",
                      "currencyCode" : "EUR"
                    },
                    "apr" : 12.75
                  }
      responses:
        "201":
          description: request to create payment card accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentCardsPostResponseBody'
              examples:
                example:
                  value: |-
                    {
                      "id" : "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1"
                    }
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Bad Request",
                      "errors" : [ {
                        "message" : "Value Exceeded. Must be between {min} and {max}.",
                        "key" : "common.api.shoesize",
                        "context" : {
                          "max" : "50",
                          "min" : "1"
                        }
                      } ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to an insufficient user quota of {quota}.",
                        "key" : "common.api.quota",
                        "context" : {
                          "quota" : "someQuota"
                        }
                      } ]
                    }
        "415":
          description: UnsupportedMediaType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Unsupported media type.",
                      "errors" : [ {
                        "message" : "The request entity has a media type {mediaType} which the resource does not support.",
                        "key" : "common.api.mediaType",
                        "context" : {
                          "mediaType" : "application/javascript"
                        }
                      } ]
                    }
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Resource not found.",
                      "errors" : [ {
                        "message" : "Unable to find the resource requested resource: {resource}.",
                        "key" : "common.api.resource",
                        "context" : {
                          "resource" : "aResource"
                        }
                      } ]
                    }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedAltError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to invalid credentials.",
                        "key" : "common.api.token",
                        "context" : {
                          "accessToken" : "expired"
                        }
                      } ]
                    }
      x-BbAccessControl-resource: WALLET
      x-BbAccessControl-function: MANAGE_PAYMENT_CARDS
      x-BbAccessControl-privilege: WRITE_PAYMENT_CARD
  /wallet/paymentcards/{cardId}:
    summary: Payment Card
    description: No description available
    get:
      tags:
      - wallet
      summary: Returns details of a specific payment card.
      description: Returns details of a specific payment card
      operationId: getCardIdByCardId
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentCard'
              examples:
                example:
                  value: |-
                    {
                      "id" : "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1",
                      "pan" : "5434111122223333",
                      "cvc" : "123",
                      "startDate" : "0116",
                      "expiryDate" : "1219",
                      "nameOnCard" : "Mr Timmy Tester",
                      "creationDate" : "2011-05-30T12:13:14+03:00",
                      "balance" : {
                        "amount" : "1000",
                        "currencyCode" : "EUR"
                      },
                      "apr" : 12.75
                    }
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Bad Request",
                      "errors" : [ {
                        "message" : "Value Exceeded. Must be between {min} and {max}.",
                        "key" : "common.api.shoesize",
                        "context" : {
                          "max" : "50",
                          "min" : "1"
                        }
                      } ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to an insufficient user quota of {quota}.",
                        "key" : "common.api.quota",
                        "context" : {
                          "quota" : "someQuota"
                        }
                      } ]
                    }
        "415":
          description: UnsupportedMediaType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Unsupported media type.",
                      "errors" : [ {
                        "message" : "The request entity has a media type {mediaType} which the resource does not support.",
                        "key" : "common.api.mediaType",
                        "context" : {
                          "mediaType" : "application/javascript"
                        }
                      } ]
                    }
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Resource not found.",
                      "errors" : [ {
                        "message" : "Unable to find the resource requested resource: {resource}.",
                        "key" : "common.api.resource",
                        "context" : {
                          "resource" : "aResource"
                        }
                      } ]
                    }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedAltError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to invalid credentials.",
                        "key" : "common.api.token",
                        "context" : {
                          "accessToken" : "expired"
                        }
                      } ]
                    }
      x-BbAccessControl-resource: WALLET
      x-BbAccessControl-function: MANAGE_PAYMENT_CARDS
      x-BbAccessControl-privilege: READ_PAYMENT_CARD
    delete:
      tags:
      - wallet
      summary: Deletes a payment card with a given id.
      description: Deletes a payment card with a given id
      operationId: deleteCardIdByCardId
      responses:
        "204":
          description: Payment card is succesfully deleted
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Bad Request",
                      "errors" : [ {
                        "message" : "Value Exceeded. Must be between {min} and {max}.",
                        "key" : "common.api.shoesize",
                        "context" : {
                          "max" : "50",
                          "min" : "1"
                        }
                      } ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to an insufficient user quota of {quota}.",
                        "key" : "common.api.quota",
                        "context" : {
                          "quota" : "someQuota"
                        }
                      } ]
                    }
        "415":
          description: UnsupportedMediaType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Unsupported media type.",
                      "errors" : [ {
                        "message" : "The request entity has a media type {mediaType} which the resource does not support.",
                        "key" : "common.api.mediaType",
                        "context" : {
                          "mediaType" : "application/javascript"
                        }
                      } ]
                    }
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Resource not found.",
                      "errors" : [ {
                        "message" : "Unable to find the resource requested resource: {resource}.",
                        "key" : "common.api.resource",
                        "context" : {
                          "resource" : "aResource"
                        }
                      } ]
                    }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedAltError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to invalid credentials.",
                        "key" : "common.api.token",
                        "context" : {
                          "accessToken" : "expired"
                        }
                      } ]
                    }
      x-BbAccessControl-resource: WALLET
      x-BbAccessControl-function: MANAGE_PAYMENT_CARDS
      x-BbAccessControl-privilege: DELETE_PAYMENT_CARD
    parameters:
    - name: cardId
      in: path
      description: No description available
      required: true
      schema:
        type: string
      examples:
        example:
          summary: example
  /bbt/build-info:
    summary: /build-info
    description: No description available
    get:
      tags:
      - bbt
      summary: Build Information.
      description: Build Information
      operationId: getBuildinfo
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BbtBuild-infoGetGetResponseBody'
              examples:
                example:
                  value: |-
                    {
                      "build-info" : {
                        "build.version" : "1.1.111-SNAPSHOT"
                      }
                    }
  /patch:
    summary: patch
    description: PATCH endpoint for test operations
    patch:
      tags:
      - patch
      summary: Patch Test.
      description: Patch Test
      operationId: patchPatch
      parameters:
      - name: X-Request-Id
        in: header
        description: Correlates HTTP requests between a client and server.
        required: false
        schema:
          type: string
        examples:
          example:
            summary: example
            value: f058ebd6-02f7-4d3f-942e-904344e8cde5
      responses:
        "200":
          description: No description available
          content: {}
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Bad Request",
                      "errors" : [ {
                        "message" : "Value Exceeded. Must be between {min} and {max}.",
                        "key" : "common.api.shoesize",
                        "context" : {
                          "max" : "50",
                          "min" : "1"
                        }
                      } ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to an insufficient user quota of {quota}.",
                        "key" : "common.api.quota",
                        "context" : {
                          "quota" : "someQuota"
                        }
                      } ]
                    }
        "415":
          description: UnsupportedMediaType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Unsupported media type.",
                      "errors" : [ {
                        "message" : "The request entity has a media type {mediaType} which the resource does not support.",
                        "key" : "common.api.mediaType",
                        "context" : {
                          "mediaType" : "application/javascript"
                        }
                      } ]
                    }
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Resource not found.",
                      "errors" : [ {
                        "message" : "Unable to find the resource requested resource: {resource}.",
                        "key" : "common.api.resource",
                        "context" : {
                          "resource" : "aResource"
                        }
                      } ]
                    }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedAltError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to invalid credentials.",
                        "key" : "common.api.token",
                        "context" : {
                          "accessToken" : "expired"
                        }
                      } ]
                    }
  /test/required-boolean-query-param:
    summary: required boolean query param
    description: arbitrary tests
    get:
      tags:
      - test
      description: No description available
      operationId: getRequiredbooleanqueryparam
      parameters:
      - name: bool
        in: query
        description: Required boolean parameter with no default value
        required: true
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: false
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequiredbooleanqueryparamGetResponseBody'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Bad Request",
                      "errors" : [ {
                        "message" : "Value Exceeded. Must be between {min} and {max}.",
                        "key" : "common.api.shoesize",
                        "context" : {
                          "max" : "50",
                          "min" : "1"
                        }
                      } ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to an insufficient user quota of {quota}.",
                        "key" : "common.api.quota",
                        "context" : {
                          "quota" : "someQuota"
                        }
                      } ]
                    }
        "415":
          description: UnsupportedMediaType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Unsupported media type.",
                      "errors" : [ {
                        "message" : "The request entity has a media type {mediaType} which the resource does not support.",
                        "key" : "common.api.mediaType",
                        "context" : {
                          "mediaType" : "application/javascript"
                        }
                      } ]
                    }
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Resource not found.",
                      "errors" : [ {
                        "message" : "Unable to find the resource requested resource: {resource}.",
                        "key" : "common.api.resource",
                        "context" : {
                          "resource" : "aResource"
                        }
                      } ]
                    }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedAltError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Access to requested resource denied.",
                      "errors" : [ {
                        "message" : "Resource access denied due to invalid credentials.",
                        "key" : "common.api.token",
                        "context" : {
                          "accessToken" : "expired"
                        }
                      } ]
                    }
  /test/values:
    summary: Test Values
    description: Test Values
    get:
      tags:
      - test
      description: No description available
      operationId: getValues
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestValuesGetResponseBody'
              examples:
                example:
                  value: |-
                    {
                      "message" : "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1",
                      "number" : "102.4"
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
  /test/headers:
    summary: Test header propagation
    description: Test header propagation
    get:
      tags:
      - test
      description: No description available
      operationId: getHeaders
      parameters:
      - name: addHops
        in: query
        description: number of additional hops to perform
        required: false
        schema:
          type: integer
          format: int32
        examples:
          example:
            summary: example
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestHeadersResponseBody'
              examples:
                example:
                  value: |-
                    {
                      "requests" : [ {
                        "name" : "building-blocks-test-wallet-presentation-service",
                        "url" : "/client-api/v1/test/headers",
                        "headers" : {
                          "correlation-id" : [ "2ed475b714a3945a" ],
                          "accept" : [ "application/json" ],
                          "x-bbt-test" : [ "X-BBT-contentVal2" ],
                          "connection" : [ "keep-alive" ]
                        }
                      }, {
                        "name" : "building-blocks-test-wallet-pandp-service",
                        "url" : "/service-api/v1/test/headers",
                        "headers" : {
                          "authorization" : [ "Bearer eyJh" ],
                          "accept" : [ "application/xml, text/xml, application/json, application/*+xml, application/*+json" ],
                          "content-type" : [ "application/json" ],
                          "x-cxt-user-token" : [ "Bearer ey" ],
                          "x-cxt-remote-user" : [ "admin" ],
                          "x-cxt-requestuuid" : [ "72002652-131a-4f28-bd00-16b8080932f5" ],
                          "correlation-id" : [ "2ed475b714a3945a" ],
                          "x-bbt-test" : [ "X-BBT-contentVal2" ]
                        }
                      }, {
                        "name" : "building-blocks-test-wallet-pandp-service",
                        "url" : "/service-api/v1/test/headers",
                        "headers" : {
                          "authorization" : [ "Bearer eyJh" ],
                          "accept" : [ "application/xml, text/xml, application/json, application/*+xml, application/*+json" ],
                          "content-type" : [ "application/json" ],
                          "x-cxt-user-token" : [ "Bearer ey" ],
                          "x-cxt-remote-user" : [ "admin" ],
                          "x-cxt-requestuuid" : [ "72002652-131a-4f28-bd00-16b8080932f5" ],
                          "correlation-id" : [ "2ed475b714a3945a" ],
                          "x-bbt-test" : [ "X-BBT-contentVal2" ]
                        }
                      } ]
                    }
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                example:
                  value: |-
                    {
                      "message" : "Description of error"
                    }
  /test/date-query-params:
    summary: dateQueryParam
    description: |
      Tests for date/time query parameters in service-apis.  Sends the same query parameters to the equivalent endpoint
      in the pandp service which echoes the given values back in the response body.  Values echoed by the pandp service
      are then returned in the response to this request.
    get:
      tags:
      - test
      description: No description available
      operationId: getDatequeryparams
      parameters:
      - name: dateTimeOnly
        in: query
        description: Creation date in datetime-only format
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: 2017-10-04T14:54:36
      - name: dateTime
        in: query
        description: Creation date in Zoned RFC3339 Date-time format
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: 2017-10-04T14:54:36Z
      - name: dateTime2616
        in: query
        description: Zoned RFC2616 Date-time param example
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: Wed, 4 Jul 2001 12:08:56 PDT
      - name: date
        in: query
        description: Date-only param example
        required: false
        schema:
          type: string
          format: date
        examples:
          example:
            summary: example
            value: 2017-10-04
      - name: time
        in: query
        description: time-only param example
        required: false
        schema:
          type: string
          format: date-time
        examples:
          example:
            summary: example
            value: 14:54:36
      responses:
        "200":
          description: No description available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateQueryParamGetResponseBody'
components:
  schemas:
    BadRequestError:
      required:
      - message
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: '#/components/schemas/ErrorItem'
    ErrorMessage:
      required:
      - message
      type: string
      description: Any further information
    BbAccessControl:
      required:
      - function
      - privilege
      - resource
      type: object
      properties:
        resource:
          type: string
          description: Resource being protected, e.g. 'User'
        function:
          type: string
          description: Business function, e.g. 'Manage Users'
        privilege:
          type: string
          description: The privilege required, e.g. 'view'
    BbApiDeprecation:
      required:
      - deprecatedFromVersion
      - description
      - reason
      - removedFromVersion
      type: object
      properties:
        deprecatedFromVersion:
          type: string
          description: Version of the product from which the endpoint has been deprecated
            and should no longer be used
          deprecated: true
        removedFromVersion:
          type: string
          description: Version of the product from which the API endpoint will be
            removed
        reason:
          type: string
          description: The reason the API endpoint was deprecated
          deprecated: true
        description:
          type: string
          description: Any further information, e.g. migration information
    BbtBuild-infoGetGetResponseBody:
      type: object
      properties:
        build-info:
          type: object
      example:
        build-info:
          build.version: 1.1.111-SNAPSHOT
    BbtbuildInfogetgetresponsebody:
      type: object
      properties:
        build-info:
          type: object
      example:
        build-info:
          build.version: 1.1.111-SNAPSHOT
    Currency:
      title: Monetary Amount
      required:
      - amount
      - currencyCode
      type: object
      properties:
        amount:
          type: string
          description: The amount in the specified currency
        currencyCode:
          pattern: ^[A-Z]{3}$
          type: string
          description: The alpha-3 code (complying with ISO 4217) of the currency
            that qualifies the amount
      description: Schema defining monetary amount in given currency.
    DateQueryParamGetResponseBody:
      type: object
      properties:
        dateTimeOnly:
          type: string
        dateTimeOnlyParsedValue:
          type: string
        dateTime:
          type: string
        dateTimeParsedValue:
          type: string
        dateTime2616:
          type: string
        dateTime2616ParsedValue:
          type: string
        date:
          type: string
        dateParsedValue:
          type: string
        time:
          type: string
        timeParsedValue:
          type: string
        formatDateTime:
          type: string
          description: The dateTime parameter formatted as 'date-time', java.util.Date
            or java.time.ZoneDateTime
          format: date-time
        formatDate:
          type: string
          description: The date parameter formatted as 'date', String or java.time.LocalDate
          format: date
        formatTime:
          type: string
          description: The time parameter formatted as 'time', String or java.time.LocalTime
        formatUtcMillisec:
          type: string
          description: The dateTime parameter formatted as 'date', long
    ErrorItem:
      type: object
      properties:
        message:
          type: string
          description: Default Message. Any further information.
        key:
          type: string
          description: '{capability-name}.api.{api-key-name}. For generated validation
            errors this is the path in the document the error resolves to. e.g. object
            name + ''.'' + field'
        context:
          type: object
          description: Context can be anything used to construct localised messages.
      description: A validation error
    ForbiddenError:
      type: object
      properties:
        message:
          type: string
          description: Any further information
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: '#/components/schemas/ErrorItem'
    InternalServerError:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: Further Information
      description: Represents HTTP 500 Internal Server Error
    NotAcceptableError:
      type: object
      properties:
        message:
          type: string
        supportedMediaTypes:
          type: array
          description: List of supported media types for this endpoint
          items:
            type: string
    NotFoundError:
      type: object
      properties:
        message:
          type: string
          description: Any further information
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: '#/components/schemas/ErrorItem'
    ObjectWrappingException:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
    PaymentCard:
      required:
      - cvc
      - expiryDate
      - id
      - nameOnCard
      - pan
      - startDate
      type: object
      properties:
        id:
          type: string
        pan:
          maxLength: 19
          type: string
          description: Must be sixteen digits, optionally in blocks of 4 separated
            by a dash
        cvc:
          maxLength: 3
          minLength: 3
          type: string
          description: Card Verification Code
        startDate:
          pattern: ^(0[1-9]|1[0-2])/?([0-9]{4}|[0-9]{2})$
          type: string
          description: 'Must be in one of these four formats: MM/YY MMYY MMYYYY MM/YYYY'
        expiryDate:
          pattern: ^(0[1-9]|1[0-2])/?([0-9]{4}|[0-9]{2})$
          type: string
          description: 'Must be in one of these four formats: MM/YY MMYY MMYYYY MM/YYYY'
        nameOnCard:
          type: string
        creationDate:
          type: string
          format: date-time
        balance:
          $ref: '#/components/schemas/Currency'
        apr:
          type: number
        cardtype:
          type: string
          enum:
          - CREDIT
          - DEBIT
          - PREPAID
    PaymentCards:
      type: array
      items:
        $ref: '#/components/schemas/PaymentCard'
    PaymentCardsPostResponseBody:
      type: object
      properties:
        id:
          type: string
      example:
        id: a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1
    RequiredbooleanqueryparamGetResponseBody:
      type: object
      properties:
        message:
          type: string
    TestHeadersResponseBody:
      type: object
      properties:
        requests:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
              headers:
                type: object
    TestValuesGetResponseBody:
      type: object
      properties:
        message:
          type: string
        number:
          type: string
      example:
        message: a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1
        number: "102.4"
    UnauthorizedAltError:
      type: object
      properties:
        message:
          type: string
          description: Any further information
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: '#/components/schemas/ErrorItem'
    UnauthorizedError:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    UnsupportedMediaTypeError:
      type: object
      properties:
        message:
          type: string
          description: Any further information
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: '#/components/schemas/ErrorItem'
